### ISSUE TITLE
Ryo's license appears to claim more than is legal

### ISSUE THREAD

**Issue by jagerman** [ryo-currency/ryo-currency#180]
Ryo's license states:

> Authors and copyright holders agree that:
> 
> 8. This licence expires and the work covered by it is released into the
> public domain on 1st of February 2020

but since some parts of Ryo are copyright Monero (or other projects), this is making a claim on behalf of other copyright holders, which you cannot legally do.  Basically Ryo holds copyright here only over additions Ryo has added and over the work as a whole, but not over all of the individual parts of that whole.  The license should be updated to reflect that.

I suggest an update to the license here to clarify that only the portions of the code for which Ryo holds the copyright enter the public domain.  I believe you could do it by modifying this part:

> Portions of this software are available under BSD-3 license. Please see ORIGINAL-LICENSE for details

On its own this doesn't seem sufficient: those portions are not merely *available* under a BSD-3 license, but rather are bound by it (and cannot be released into the public domain since you are not the copyright holder).

A change to the following might work:

```
The software includes portions not copyright Ryo Currency Project, which are provided under a BSD-3 license as described in ORIGINAL-LICENSE.

The work as a whole and all individual portions of the code copyright Ryo Currency Project fall under the following license terms:
```

**Comment by fireice-uk** [comment]
I believe this is more applicable to ryo-libre than this repository

https://github.com/ryo-currency/ryo-libre/blob/master/src/cryptonote_protocol/block_queue.cpp#L4-L7

However, if you would like to make it crystal clear I think this change is better:

> Portions of this software are additionally dual-licenced under  BSD-3 license. Please see ORIGINAL-LICENSE for details

**Comment by jagerman** [comment]
> I believe this is more applicable to ryo-libre than this repository

Yes, the license there is perfectly fine.

> However, if you would like to make it crystal clear I think this change is better: ...

I think that suffers from the same problem, however: you don't hold the copyright over some of the code and thus cannot re-license it to something (public domain) that does not preserve the requirements of the original license.  Or in other words: the license (or *all* of the licenses, if available under multiple) must conform with the original license's requirements.

**Comment by fireice-uk** [comment]
> I think that suffers from the same problem, however:

Please explain how you arrived at this conclusion - OpenSSL has been dual-licenced for around 20 years for exactly the same reason that you described.

**Comment by jagerman** [comment]
> Please explain how you arrived at this conclusion - OpenSSL has been dual-licenced for around 20 years for exactly the same reason that you described.

OpenSSL's license is a conjunctive dual license which isn't what is commonly meant by a dual license (For instance see https://en.wikipedia.org/wiki/Multi-licensing).  Software using OpenSSL must comply with the terms of *both* licenses.

The terminology of "are additionally dual-licenced with BSD-3 ..." is rather imprecise for the above reason.  I'd suggest "are additionally subject to the terms of the BSD-3 ..." to avoid ambiguity.

**Comment by fireice-uk** [comment]
> are additionally subject to the terms of the BSD-3 ...

Sounds ok. 

May I have a quick question? I found the law module of my Computer Forensics BSc to be most boring, yet Monero guys can't seem to peel themselves away from the licence. This is the second issue about it. There are much more interesting parts elsewhere - what's up with that?

**Comment by erciccione** [comment]
@fireice-uk Why close this issue if the problem hasn't been solved? Please fix the license, because as the OP says: 

> some parts of Ryo are copyright Monero (or other projects), this is making a claim on behalf of other copyright holders, which you cannot legally do

Please fix.

**Comment by fireice-uk** [comment]
Please reply

```
May I have a quick question? I found the law module of my Computer Forensics BSc to be most boring, yet Monero guys can't seem to peel themselves away from the licence. This is the second issue about it. There are much more interesting parts elsewhere - what's up with that?
```

**Comment by fireice-uk** [comment]
For some extra laughs, let's remind ourselves of that time Monero tried to claim authorship of the BSD licence. https://github.com/ryo-currency/ryo-currency/issues/135

**Comment by erciccione** [comment]
> Please reply

Sure. I find very interesting that a project lead by a person who attacks Monero every other day is using an illegal license which *is making a claim on behalf of other copyright holders [Monero], which you cannot legally do*. 

I'm sure the Ryo team will make the morally and legally correct choice, adding the lines suggested by @jagerman. That way appropriate credits will be given. This shouldn't be an issue at all in the first place, especially considering that Ryo codebase is for the vast majority pulled from Monero.

I believe giving credits correctly to other projects/contributors is the base of every open source project (and not only them), especially since Monero is a project run moslty by volunteer, who have no money incentive or a dev fund at their disposal, but only the satisfaction of having their work properly credited to them. In this moment Ryo is not giving credits as it should in its license. As a Monero contributor, i wish that to be fixed.

Also, i think asking people who point out (correctly) an issue why they pointed it out it's a very weird approach. A problem was rised and you acknowledged its validity, but refuse to fix it. Why?

**Comment by Ryo-RU** [comment]
[erciccione](https://github.com/erciccione), don't forget about monero habit removing contributors names, example is [here  ](https://twitter.com/fireice_uk/status/1067750614359265281)

**Comment by erciccione** [comment]
> erciccione, don't forget about monero habit removing contributor names, example is here 

That didn't happen in an official Monero repository, the issue was fixed the exact moment it has been pointed out and the author of the mistake acknowledged he made an error, gave a valid explanation of why the mistake was made and apologized, which is the correct approach. A non correct approach would be to close an issue without fixing the problem rised and attack the person who opened the issue. Sounds familiar?

Beside, your comment is off-topic. I don't see how that tweet is related to this issue (beside, of course, the irresistible urgence to attack Monero).

**Comment by BoredAlchemist** [comment]
Maybe Monero should worry about fixing it’s code over faux complaining about the licence choice of others. 
Do you monero guys have the law and the exact lines of text that show what you think is being violated or is this just feelings

**Comment by BoredAlchemist** [comment]
Maybe Monero should worry about fixing it’s code over faux complaining about the licence choice of others.
Do you monero guys have the law and the exact lines of text that show what you think is being violated or is this just feelings

**Comment by Ryo-RU** [comment]
@erciccione Contribute to official Monero repository, have your contribution [used by mindless fanboys](https://twitter.com/dotnwat/status/958961534125813760) to bludgeon other projects

**Comment by fireice-uk** [comment]
> I believe giving credits correctly to other projects/contributors is the base of every open source project (and not only them), especially since Monero is a project run moslty by volunteer,

I see that you haven't even read what the issue is about since it isn't about credits. Let me address the actual issue first first, then we will come back to that.

> This licence expires and the work covered by it is released into the public domain on 1st of February 2020

Work covered by the licence is our own work. There are no further claims. That''s my legal option. Whatever parts are not changed are still covered by the BSD licence. This is very similar to the way OpenSSL was licenced for a long while.

Now. I'm not sure which scenario applies here to you in particular @erciccione so I will list all of them and let you pick-and-choose.

- **You genuinely believe you are right despite not knowing what the issue is about**
Get a legal opinion in writing form someone qualified and acting on the behalf of the copyright holder.

- **You are trying to suck up to someone higher up than you, maybe the [saviour of the space shuttle / NASA](https://moneromonitor.com/episodes/2017-04-10-Episode-002.html)?**
I think your job is done then, you can go home.

- **You got hopped up on a quasi-religious experience during the Church of Monero or some other community meeting and you came here because someone gave you the link.**
My condolences.

**Comment by erciccione** [comment]
@fireice-uk i won't answer to your delirium, but only the statements that actually make some sense:

>  it isn't about credits

You are wrong. When you say `Authors and copyright holders agree that:[...]`, you are making claims on behalf of Monero contributors and you cannot. Let's not call it 'credits' if that bothers you.

Also, the comparison to OpenSSL doesn't really hold up, as explained [in this comment](https://github.com/ryo-currency/ryo-currency/issues/180#issuecomment-466848920) and [you acknowledge it](https://github.com/ryo-currency/ryo-currency/issues/180#issuecomment-467391265).

The point is (quoting @jagerman) *the license (or all of the licenses, if available under multiple) must conform with the original license's requirements.*
Ryo is in clear violation of Monero's license. As we can see from this thread you acknowledged that is true, but still refuse to fix it. So i will ask again: Why?

**Comment by fireice-uk** [comment]
>  Let's not call it 'credits' if that bothers you.

How did you arrive at it being credits to Monero authors exactly?

> As we can see from this thread you acknowledged that is true, but still refuse to fix it. 

I think you are seeing things you want to see, rather than things that are there.

> you are making claims on behalf of Monero contributors and you cannot

Let me explain it in a real simple fashion. I don't make any statements. The licence does. The licence applies to our code. It is perfectly simple if you are not a zealot looking for a fight.
